<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-9J1KF08" ignored="2" name="Test" tests="2" failures="1" timestamp="16 May 2020 07:05:52 GMT" time="32.026" errors="0">
  <testcase name="Login" time="3.131" classname="com.qa.TestCases.LoginTest"/>
  <testcase name="Customer" time="11.025" classname="com.qa.TestCases.CustomerTest">
    <failure type="java.lang.AssertionError" message="expected [Customers Registered Successfully!!!] but found [Customer Registered Successfully!!!]">
      <![CDATA[java.lang.AssertionError: expected [Customers Registered Successfully!!!] but found [Customer Registered Successfully!!!]
at com.qa.TestCases.CustomerTest.Customer(CustomerTest.java:42)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Customer -->
  <testcase name="DataDriven" time="0.0" classname="com.qa.TestCases.CustomerTest">
    <ignored/>
  </testcase> <!-- DataDriven -->
  <testcase name="DataDriven" time="0.0" classname="com.qa.TestCases.LoginTest">
    <ignored/>
  </testcase> <!-- DataDriven -->
</testsuite> <!-- Test -->
